version: 0.1
#
# eb_codebuild_settings:
#   CodeBuildServiceRole: arn:aws:iam::062773471215:role/service-role/codebuild-oneroost-service-role
#   ComputeType: BUILD_GENERAL1_SMALL
#   Image: aws/codebuild/eb-nodejs-4.4.6-amazonlinux-64:2.1.3
#   Timeout: 30

phases:
  install:
    commands:
      - echo dumping all environment variables
      - printenv
    #   - echo putting CODEBUILD_BUILD_ID=$CODEBUILD_BUILD_ID into file
    #   - echo "export const build_id = \"$CODEBUILD_BUILD_ID\"" > codebuild_build.js
      - echo "NODE_ENV = $NODE_ENV"
      - echo putting pipeline info into file
      - aws codepipeline --region us-east-1 get-pipeline-state --name $PIPELINE --output json > pipeline.json
      - echo intalling babel globally
      - npm install -g babel
      - echo Installing Yarn...
      - npm install -g yarn
      - npm install node-sass
      - echo Installing gulp...
      - npm install -g gulp
      - echo installing jest...
      - npm install -g jest
      - echo checking location of gulp and its version
      - which gulp && gulp -v
    #   - echo install sentry-cli
    #   - curl -sL https://sentry.io/get-cli/ | bash
    #   - echo checking sentry installed correctly at
    #   - which sentry-cli
  pre_build:
    commands:
      - echo Installing source Yarn dependencies...
      - yarn install --production=false
    #   - echo log into sentry with auth token
    #   - sentry-cli info
  build:
    commands:
      - echo Build started on `date`
      - echo starting the gulp build process
      - gulp version
      - gulp install
      - echo source directory = $CODEBUILD_SRC_DIR
      - echo printing all files in the public directory
      - ls public/bundle
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - .ebextensions/**/*
    - .elasticbeanstalk/**/*
    - buildspec.yml
    - main.js
    - cloud/**/*
    - package.json
    - public/**/*
    - yarn.lock
