version: 0.1

phases:
  install:
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
      - npm install node-sass
      - echo Installing gulp...
      - npm install -g gulp
      - echo checking location of gulp and its version
      - which gulp && gulp -v
  pre_build:
    commands:
      - echo Installing source Yarn dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo starting the gulp build process
      - gulp build:all
  post_build:
    commands:
      - echo Build completed on `date`
# artifacts:
#   files:
#     - HelloWorld.js
