version: 0.1
#
# eb_codebuild_settings:
#   CodeBuildServiceRole: arn:aws:iam::062773471215:role/service-role/codebuild-oneroost-service-role
#   ComputeType: BUILD_GENERAL1_SMALL
#   Image: aws/codebuild/eb-nodejs-4.4.6-amazonlinux-64:2.1.3
#   Timeout: 30

phases:
  install:
    commands:
      - echo list files
      - ls
      - echo Installing Yarn...
      - npm install -g yarn
      - npm install node-sass
      - echo Installing gulp...
      - npm install -g gulp
      - echo checking location of gulp and its version
      - which gulp && gulp -v
  pre_build:
    commands:
      - echo Installing source Yarn dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo starting the gulp build process
      - gulp build:all
      - echo build:all conmpleted... zipping...
      - echo source directory = $CODEBUILD_SRC_DIR
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - .ebextensions/**/*
    - .elasticbeanstalk/**/*
    - buildspec.yml
    - main.js
    - cloud/**/*
    - package.json
    - public/**/*
    - yarn.lock
