version: 0.1

phases:
  install:
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
      - npm install node-sass
      - echo Installing gulp...
      - npm install -g gulp

  pre_build:
    commands:
      - echo Installing source Yarn dependencies...
      - yarn install --production
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - gulp build
  post_build:
    commands:
      - echo Build completed on `date`
# artifacts:
#   files:
#     - HelloWorld.js
